### ISSUE TITLE
Integrate CodeMirror's matchtags.js

### ISSUE THREAD

**Issue by tomma5o** [alexzaworski/CodePen-Enhancement-Suite#1]
Is very useful for me integrate a matching tags in html editor in codepen, and i don't know why codepen don't integrate it

**Comment by alexzaworski** [comment]
Hi Tommaso,

This is what you're talking about right?
https://codemirror.net/demo/matchtags.html

Is it the jumping to the closing tag or the highlighting that you find useful? It may be possible to get the highlighting up and running but I'm super hesitant to adjust the way the editor is initialized (if that's even possible) since I'd imagine the odds of breaking something are preeeeetty high.

**Comment by alexzaworski** [comment]
Ah so it looks like tag matching has to be set on initialization, I don't see a way to change it after the fact at all and since it isn't enabled the appropriate styling hooks aren't added at all.

Unfortunately this doesn't look like it's going to be feasible so I'm going to close the issue— if you have an idea on how to implement it I'm open to exploring this further.

**Comment by alexzaworski** [comment]
Hey @tomma5o just a heads up, I actually hit up CodePen support about this since it _does_ seem pretty smart, they said it's been on the to-do list for a while and it'll probably get added at some point but they don't have a timeline.

**Comment by tomma5o** [comment]
WOW! Thanks @alexzaworski 👍  !
