### ISSUE TITLE
Autocomplete dropdown transparent

### ISSUE THREAD

**Issue by ricardozea** [alexzaworski/CodePen-Enhancement-Suite#2]
Let me start by saying that this extension is 💯

However, as you can see in the following screenshot, the autocomplete dropdown appears transparent when using the extension. I was just using the Monokai theme and that's it. Not sure if this is me or the extension but just wanted to let you know.

![image](https://cloud.githubusercontent.com/assets/1656481/21489806/6fb36926-cbbc-11e6-943a-b0a2cd3f917d.png)

**Comment by alexzaworski** [comment]
Hi Ricardo :)

This is 100% a problem with the extension, I've actually noticed it in past and totally forgot to patch it. I'll see if I can figure out a fix early this week, custom theme stuff gets really dicey sometimes because there's a lot of random editor stuff tucked into the CSS of the themes CodePen uses natively.

Glad you're likely things so far-- thanks so much for reporting this.

**Comment by alexzaworski** [comment]
This should be fixed with ed1c333e. I just published v0.7.1, typically it takes an hour or so and then it'll be available. If you go to `chrome://extensions` and check "Developer Mode" (top right) you'll get an `Update extensions now` button that you can use to force an update (I think by default they happen every few hours, not sure).

If you click that in an hour or so from now you should be all set— thanks again!

**Comment by ricardozea** [comment]
It works great!

Thanks for fixing and fast turnaround.
