### ISSUE TITLE
Ultra-widescreen mode with four columns

### ISSUE THREAD

**Issue by smart-medi** [alexzaworski/CodePen-Enhancement-Suite#8]
![ultrawide_four-in-line](https://user-images.githubusercontent.com/43875466/67263491-f696a500-f4b0-11e9-8e49-1619bb0b13f4.png)

Could you please implement a four pane linear view? Currently there isn't any proper mode for ultrawide screens.

Lauri

**Comment by alexzaworski** [comment]
Hi Lauri,

Thanks for the suggestion! I'm not going to be implemeting this since you can get quite close with `live` view by:

- Maximizing the editors in an editors-on-top layout
- Putting the window with your live-view Pen next to them

I appreciate that you took the time to include a screenshot though-- envious of your monitor width :)
